In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

from gensim.models import word2vec, KeyedVectors
from tqdm import tqdm
tqdm.pandas()

/Users/shinichiro.saito/opt/anaconda3/lib/python3.8/site-packages/tqdm/std.py:668: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel

In [2]:
sub = pd.read_csv('../../data/atmacup10__sample_submission.csv')
color = pd.read_csv('../../data/color.csv')
historical_person = pd.read_csv('../../data/historical_person.csv')
maker = pd.read_csv('../../data/maker.csv')
material = pd.read_csv('../../data/material.csv')
collection = pd.read_csv('../../data/object_collection.csv')
palette = pd.read_csv('../../data/palette.csv')
principal_maker_occupation = pd.read_csv('../../data/principal_maker_occupation.csv')
principal_maker = pd.read_csv('../../data/principal_maker.csv')
production_place = pd.read_csv('../../data/production_place.csv')
technique = pd.read_csv('../../data/technique.csv')
test = pd.read_csv('../../data/test.csv')
train = pd.read_csv('../../data/train.csv')

In [3]:
from geopy.geocoders import Nominatim
import numpy as np

def place2country(address):
    geolocator = Nominatim(user_agent='sample', timeout=200)
    loc = geolocator.geocode(address, language='en')
    coordinates = (loc.latitude, loc.longitude)
    location = geolocator.reverse(coordinates, language='en')
    country = location.raw['address']['country']
    return country

In [4]:
from tqdm import tqdm_notebook as tqdm

place_list = production_place['name'].unique()
country_dict = {}
for place in tqdm(place_list):
    if place != place:
        continue
    try:
        country = place2country(place)
        country_dict[place] = country
    except:
        # 国名を取得できない場合はnan
        print(place)
        country_dict[place] = np.nan

<ipython-input-4-25aa529dbafa>:5: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for place in tqdm(place_list):

HBox(children=(FloatProgress(value=0.0, max=144.0), HTML(value='')))

Indonesian Archipelago

In [5]:
production_place['country_name'] = production_place['name'].map(country_dict)
production_place.head()

              object_id                  name country_name
0  0012765f7a97ccc3e9e9           Netherlands  Netherlands
1  00133be3ff222c9b74b0             Amsterdam  Netherlands
2  00133be3ff222c9b74b0  Northern Netherlands  Netherlands
3  0017be8caa87206532cb             Amsterdam  Netherlands
4  001b2b8c9d3aa1534dfe              Suriname     Suriname

In [6]:
production_place.to_csv('../production_place_rename.csv')

In [15]:
from tqdm import tqdm_notebook as tqdm

place_of_birth_list = maker['place_of_birth'].unique()
country_dict = {}
for place in tqdm(place_of_birth_list):
    if place != place:
        continue
    try:
        country = place2country(place)
        country_dict[place] = country
    except:
        # 国名を取得できない場合はnan
        print(place)
        country_dict[place] = np.nan

<ipython-input-15-5126e935f6a8>:5: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for place in tqdm(place_of_birth_list):

HBox(children=(FloatProgress(value=0.0, max=568.0), HTML(value='')))

Kralingen-Ambacht
Brembate Superiore
Rio Demerary
Monte Scùdolo
Fuentedetodos
Baierrain
Zwollerkerspel
Wehlerad
Kalimaro (Ned.Indië)
Honjo Warigesui
Théâtre des Folies-Marigny
Goëngamieden

In [16]:
country_dict

{"'s-Heerenberg": 'Netherlands',
 'Amsterdam': 'Netherlands',
 'Utrecht': 'Netherlands',
 'Gorinchem': 'Netherlands',
 'Antwerpen': 'Belgium',
 'Rotterdam': 'Netherlands',
 'Leiden': 'Netherlands',
 'Den Haag': 'Netherlands',
 'Delft': 'Netherlands',
 'Frankfurt am Main': 'Germany',
 'Lisse': 'Netherlands',
 'Groningen': 'Netherlands',
 'Dordrecht': 'Netherlands',
 'Haarlem': 'Netherlands',
 'Leeuwarden': 'Netherlands',
 'Parijs': 'France',
 'Brussel': 'Belgium',
 'Schiedam': 'Netherlands',
 'Londen': 'United Kingdom',
 'Wenen': 'Austria',
 'Kortrijk': 'Belgium',
 'Mandal': 'Mongolia',
 'Sainte-Croix': 'France',
 'Marseille': 'France',
 'Tilburg': 'Netherlands',
 'Oudenaarde': 'Belgium',
 'Schagen': 'Netherlands',
 'Rijswijk': 'Netherlands',
 'Kralingen-Ambacht': nan,
 'Ouderkerk aan de Amstel': 'Netherlands',
 'Zaltbommel': 'Netherlands',
 'Florence': 'Italy',
 'Bologna': 'Italy',
 'Battedizzo': 'Italy',
 'Hoorn': 'Netherlands',
 'Blois': 'France',
 'Enkhuizen': 'Netherlands',
 'Titisee-Neustadt': 'Germany',
 'Busseto': 'Italy',
 'Altdorf': 'Switzerland',
 'Neurenberg': 'Germany',
 'Genua': 'Italy',
 'Maassluis': 'Netherlands',
 'Vevey': 'Switzerland',
 'Morlaix': 'France',
 'Saint-Omer': 'France',
 'Hoboken': 'United States',
 'Dresden': 'Germany',
 'Alkmaar': 'Netherlands',
 'Frankrijk': 'France',
 'Lyon': 'France',
 'Manche': 'France',
 'Mantua': 'Italy',
 'Brembate Superiore': nan,
 'Napels': 'Italy',
 'München': 'Germany',
 'Montargis': 'France',
 'Montfoort': 'Netherlands',
 'Lille': 'France',
 'Nijmegen': 'Netherlands',
 'Middelburg': 'Netherlands',
 'Teheran': 'Iran',
 'Montdidier': 'France',
 'Bagnolet': 'France',
 'Terneuzen': 'Netherlands',
 'Zaandam': 'Netherlands',
 'Aussig': 'Czechia',
 'Arnhem': 'Netherlands',
 'Albano Laziale': 'Italy',
 'Este': 'Italy',
 "'s-Hertogenbosch": 'Netherlands',
 'Berlijn': 'Germany',
 'Nottingham': 'United Kingdom',
 'Mannheim': 'Germany',
 'Paramaribo': 'Suriname',
 'Doornik': 'Belgium',
 'Loiret': 'France',
 'Oise': 'France',
 'Ribeauvillé': 'France',
 'Mariestad': 'Sweden',
 'Oude Pekela': 'Netherlands',
 'Altona': 'Germany',
 'Rouen': 'France',
 'Kampen': 'Netherlands',
 'Middenbeemster': 'Netherlands',
 'Vlissingen': 'Netherlands',
 'Trier': 'Germany',
 'Deventer': 'Netherlands',
 'Keulen': 'Germany',
 'Straatsburg': 'France',
 'Orzinuovi': 'Italy',
 'Milaan': 'Italy',
 'Murano': 'Italy',
 'Sevilla': 'Spain',
 'Meeuwen': 'Netherlands',
 'Verona': 'Italy',
 'Venetië': 'Italy',
 'Arcisate': 'Italy',
 'Lausanne': 'Switzerland',
 'Harlingen': 'United States',
 'Dessau': 'Germany',
 'Franeker': 'Netherlands',
 'Batenburg': 'Netherlands',
 'Siena': 'China',
 'Cotignola': 'Italy',
 'Weesp': 'Netherlands',
 'Bussum': 'Netherlands',
 'Bolsward': 'Netherlands',
 'Nijehaske': 'Netherlands',
 'Steenwijk': 'Netherlands',
 'Königsberg': 'Russia',
 'Breda': 'Netherlands',
 'Nymphenburg': 'Germany',
 'Kopenhagen': 'Denmark',
 'Stockholm': 'Sweden',
 'Schwerin': 'Germany',
 'Krefeld': 'Germany',
 'Hamburg': 'Germany',
 'Soest (Duitsland)': 'Germany',
 'New York': 'United States',
 'Italië': 'Italy',
 'Treviso': 'Italy',
 'Camerano': 'Italy',
 'Tronzano Vercellese': 'Italy',
 'Heidelberg': 'Germany',
 'Amersfoort': 'Netherlands',
 'Aken': 'Germany',
 'Portsmouth': 'United Kingdom',
 'Grasse': 'France',
 'Deinze': 'Belgium',
 'Brooklyn': 'United States',
 'Karlsruhe': 'Germany',
 'Kralingen': 'Netherlands',
 'Southampton': 'United Kingdom',
 'Geraardsbergen': 'Belgium',
 'Middlesex': 'United Kingdom',
 'Hoxton': 'United Kingdom',
 'Mechelen': 'Belgium',
 'Semarang': 'Indonesia',
 'Bad Salzungen': 'Germany',
 'Bremen': 'Germany',
 'West-Sumatra': 'Indonesia',
 'Oosterhout': 'Netherlands',
 'Böblingen': 'Germany',
 'Stettin': 'Poland',
 'Roermond': 'Netherlands',
 'Durgerdam': 'Netherlands',
 'West Carlisle': 'United States',
 'Chamagne': 'France',
 'Abbeville': 'France',
 'Tours': 'France',
 'Isère': 'France',
 'Schotland': 'United Kingdom',
 'Winterthur': 'Switzerland',
 'Zürich': 'Switzerland',
 'Dendermonde': 'Belgium',
 'Loire-Atlantique': 'France',
 'Sèvres': 'France',
 'Vilvoorde': 'Belgium',
 'Velsen': 'Netherlands',
 'Lier': 'Belgium',
 'Edam': 'Netherlands',
 'Gouda': 'Netherlands',
 'Bergen op Zoom': 'Netherlands',
 'Monster': 'Germany',
 'Arnemuiden': 'Netherlands',
 'Warschau': 'Poland',
 'Sedan': 'France',
 'Ardwick': 'United Kingdom',
 'Chivasso': 'Italy',
 'Almelo': 'Netherlands',
 'Heusden': 'Netherlands',
 'Wijk bij Duurstede': 'Netherlands',
 'Zwolle': 'Netherlands',
 'Tiel': 'Netherlands',
 'Rome': 'Italy',
 'Bodegraven': 'Netherlands',
 'Düsseldorf': 'Germany',
 'Caen': 'France',
 'Stuttgart': 'Germany',
 'Brugge': 'Belgium',
 'Gent': 'Belgium',
 'Hilscheid': 'Germany',
 'Barnstaple': 'United Kingdom',
 'Westminster': 'United Kingdom',
 'Nigtevecht': 'Netherlands',
 'Kreta': 'Greece',
 'Paderborn': 'Germany',
 'Rio Demerary': nan,
 'Versailles': 'France',
 'Triel-sur-Seine': 'France',
 'Nièvre': 'France',
 'Eindhoven': 'Netherlands',
 'Fareins': 'France',
 'Woerden': 'Netherlands',
 'Châteauroux': 'France',
 'Charenton-Saint-Maurice': 'France',
 'Warneton': 'France',
 'Jersey City': 'United States',
 'Vollenhove': 'Netherlands',
 'Nantes': 'France',
 'Neustrelitz': 'Germany',
 'Termonde': 'Belgium',
 'Prato': 'Italy',
 'Protzan': 'Poland',
 'Vicchio': 'Italy',
 'Stilo': 'Italy',
 'Bassano del Grappa': 'Italy',
 'Monte Scùdolo': nan,
 'Canale di Serino': 'Italy',
 'Padua': 'Italy',
 'Capodistria': 'Slovenia',
 'Camberwell': 'United Kingdom',
 'Chesterfield': 'United States',
 'Aberdeenshire': 'United Kingdom',
 'Fuentedetodos': nan,
 'Weil of Colmar': 'France',
 'Beieren': 'Germany',
 'Maagdenburg': 'Germany',
 'Baierrain': nan,
 'Alt-Breisach': 'Germany',
 'Dorsten': 'Germany',
 'Harderwijk': 'Netherlands',
 'Vaugirard': 'France',
 'Haute-Savoie': 'France',
 'Charleroi': 'Belgium',
 'Granville': 'France',
 'Josselin': 'France',
 'Somme': 'France',
 'Bridgwater': 'United Kingdom',
 'Emden': 'Germany',
 'Maastricht': 'Netherlands',
 'Elberfeld': 'Germany',
 'Danzig': 'Poland',
 'Kreuznach': 'Germany',
 'Hannover': 'Germany',
 'Leipzig': 'Germany',
 'Handschuhsheim': 'Germany',
 'Genève': 'Switzerland',
 'Saint-Hippolyte-du-Fort': 'France',
 'Pas-de-Calais': 'France',
 'Orléans': 'France',
 'Ferrara (stad)': 'Italy',
 'Sacco': 'Italy',
 'Belluno': 'Italy',
 'Valduggia': 'Italy',
 'Batavia': 'Indonesia',
 'Regensburg': 'Germany',
 'Koblenz': 'Germany',
 'Chicago': 'United States',
 'Brielle': 'Netherlands',
 'Alvah Aberdeenshire': 'United Kingdom',
 'Pyrénées-Atlantiques': 'France',
 'Luik': 'Belgium',
 'Rheinbach': 'Germany',
 'Tuttlingen': 'Germany',
 'Zwollerkerspel': nan,
 'Nieuwer-Amstel': 'Netherlands',
 'Iowa': 'United States',
 'Pozzuoli': 'Italy',
 'Marone': 'Italy',
 'Bondio': 'Central African Republic',
 'Châteaudun': 'France',
 'Doesburg': 'Netherlands',
 'Hulst': 'Netherlands',
 'Trento': 'Italy',
 'Mogliano Veneto': 'Italy',
 'Vicenza': 'Italy',
 'Sassoferrato': 'Italy',
 'Gabella': 'Italy',
 'Parma': 'Italy',
 'Sermoneta': 'Italy',
 'Santa Croce': 'Italy',
 'Sicilië': 'Italy',
 'Monza': 'Italy',
 'Udine': 'Italy',
 'Livorno': 'Italy',
 'Corleone': 'Italy',
 'Forno di Canale': 'Italy',
 'Made': 'Indonesia',
 'Leuven': 'Belgium',
 'Wehlerad': nan,
 'Augsburg': 'Germany',
 'Lübeck': 'Germany',
 'Kleef': 'Germany',
 'Cento': 'Italy',
 'Wismar': 'Germany',
 'Calvenzano': 'Italy',
 'Turijn': 'Italy',
 'Apeldoorn': 'Netherlands',
 'Ornans': 'France',
 'Villiers-le-Bel': 'France',
 'Grenoble': 'France',
 'Veendam': 'Netherlands',
 'Bernau': 'Germany',
 'Zoeterwoude': 'Netherlands',
 'Wier': 'Netherlands',
 'Huissen': 'Netherlands',
 'Soerabaja': 'Netherlands',
 'Bautzen': 'Germany',
 'Bracht': 'Germany',
 'Duffel': 'Belgium',
 'Ruinen': 'Netherlands',
 'Vrouwenpolder': 'Netherlands',
 'Baambrugge': 'Netherlands',
 'Veere': 'Netherlands',
 'Terwolde': 'Netherlands',
 'Hamm': 'Germany',
 'Albi': 'France',
 'Canterbury': 'United Kingdom',
 'Olney': 'United States',
 'Zeist': 'Netherlands',
 'Lage Vuursche': 'Netherlands',
 'Heemstede': 'Netherlands',
 'Darmstadt': 'Germany',
 'Breslau': 'Poland',
 'Ezinge': 'Netherlands',
 'Beaune': 'France',
 'onbekend': 'Netherlands',
 'Azcoitia': 'Spain',
 'Nancy': 'France',
 'Zierikzee': 'Netherlands',
 'Goes': 'France',
 'Wormer': 'Netherlands',
 'Sint-Eustatius': 'Netherlands',
 'Dokkum': 'Netherlands',
 "'s-Gravendeel": 'Netherlands',
 'Hochdorf': 'Germany',
 'Cochem': 'Germany',
 'Frankenthal': 'Germany',
 'Zuiderzee': 'Netherlands',
 'Sluis': 'Netherlands',
 'Fontainebleau': 'France',
 'Oost-Souburg': 'Netherlands',
 'Bordeaux': 'France',
 'Bey-sur-Seille': 'France',
 'Duitsland': 'Germany',
 'Lowell': 'United States',
 'Cumbria': 'United Kingdom',
 'Hamilton': 'Canada',
 'Hilversum': 'Netherlands',
 'Medemblik': 'Netherlands',
 'Culemborg': 'Netherlands',
 'Dieppe': 'France',
 'Boskoop': 'Netherlands',
 'Noord-Holland': 'Netherlands',
 'Beverwijk': 'Netherlands',
 'Kalimaro (Ned.Indië)': nan,
 'De Rijp': 'Netherlands',
 'Delfshaven': 'Netherlands',
 'Meppel': 'Netherlands',
 'Rees': 'Germany',
 'Beveren': 'Belgium',
 'Ieper': 'Belgium',
 'Poerworedjo': 'Suriname',
 'Purmerend': 'Netherlands',
 'Toruń': 'Poland',
 'Monnickendam': 'Netherlands',
 'Abcoude': 'Netherlands',
 'Kasteel Herbeke': 'Belgium',
 'Naarden': 'Netherlands',
 'Middelharnis': 'Netherlands',
 'Vianen': 'Netherlands',
 'Schoorl': 'Netherlands',
 'Kwaremont': 'Belgium',
 'Breskens': 'Netherlands',
 'Auch': 'France',
 'Praag': 'Czechia',
 'Metz': 'France',
 'Valenciennes': 'France',
 'Reims': 'France',
 'Saint-Mihiel': 'France',
 'Gruchy': 'France',
 'Arles': 'France',
 'Cantal': 'France',
 'Tournus': 'France',
 'Gdansk': 'Poland',
 'Wacken': 'Germany',
 'Lattrop': 'Netherlands',
 'Bergen': 'Norway',
 'Buch': 'Germany',
 'Hof (Duitsland)': 'Germany',
 'Wagstadt': 'Czechia',
 'Ilmenau': 'Germany',
 'Neuss': 'Germany',
 'Biberach an der Riß': 'Germany',
 'Hagen': 'Germany',
 'Haina': 'China',
 'Altenburg': 'Germany',
 'Geesteren': 'Netherlands',
 'Bangka': 'Indonesia',
 'Hooge Zwaluwe': 'Netherlands',
 'Hedel': 'Netherlands',
 'Ambon': 'France',
 'Overveen': 'Netherlands',
 'Geertruidenberg': 'Netherlands',
 'Uithoorn': 'Netherlands',
 'Zutphen': 'Netherlands',
 'Grafton': 'Australia',
 'Boston': 'United States',
 'Manchester': 'United Kingdom',
 'Old Brentford': 'United Kingdom',
 'Fife': 'United Kingdom',
 'Daventry': 'United Kingdom',
 'Edinburgh': 'United Kingdom',
 'Kassel': 'Germany',
 'Carpentras': 'France',
 'Albertville': 'France',
 'Épinal': 'France',
 'Ekeren': 'Belgium',
 'Oostakker': 'Belgium',
 'Bazel': 'Switzerland',
 'Cuenca': 'Spain',
 'Avilés': 'Spain',
 'Zaragoza': 'Spain',
 'Braine': 'France',
 'Kolkata': 'India',
 'Ath': 'United States',
 'Hongarije': 'Hungary',
 'Wuppertal': 'Germany',
 'Játiva': 'Spain',
 'Tönning': 'Germany',
 'Kioto': 'Japan',
 'Meulebeke': 'Belgium',
 'Neuruppin': 'Germany',
 'Chemnitz': 'Germany',
 'Jogjakarta': 'Indonesia',
 'Honjo Warigesui': nan,
 'Edo': 'Nigeria',
 'Odda': 'Norway',
 'Ruigezand': 'Netherlands',
 'Krakau': 'Poland',
 'Uttar Pradesh': 'India',
 'Staphorst': 'Netherlands',
 'Pistoia': 'Italy',
 'Mecklenburg-Voor-Pommeren': 'Germany',
 'Cheshire': 'United Kingdom',
 'Oshkosh': 'United States',
 'Deux-Sèvres': 'France',
 'Nîmes': 'France',
 'Rennes': 'France',
 'Dijon': 'France',
 'Champel': 'Switzerland',
 'Vorden': 'Netherlands',
 'Sainte-Menehould': 'France',
 'Dronrijp': 'Netherlands',
 'Woudrichem': 'Netherlands',
 'Cortona': 'Italy',
 'Kronach': 'Germany',
 'Wittenberg': 'Germany',
 'Overschie': 'Netherlands',
 'Timisoara': 'Romania',
 'Bacsborsod': 'Hungary',
 'Limoges': 'France',
 'Heemskerk': 'Netherlands',
 'Como': 'Italy',
 'Weimar': 'Germany',
 'Kaapstad': 'South Africa',
 'Niemtschitz': 'Czechia',
 'Oldehove': 'Netherlands',
 'Tannheim': 'Germany',
 'Burgos': 'Spain',
 'Lake George': 'United States',
 'Laon': 'France',
 'Zuid-Vlaanderen': 'Belgium',
 'Pruisen': 'Belgium',
 'Mariënbad': 'Czechia',
 'Philippine': 'Netherlands',
 'Forli': 'Italy',
 'Steinlah': 'Germany',
 'Santvliet': 'Belgium',
 'Foligno': 'Italy',
 'Maarsseveen': 'Netherlands',
 'Schellingwoude': 'Netherlands',
 'Scherpenzeel': 'Netherlands',
 'Loir-et-Cher': 'France',
 'Lunéville': 'France',
 'Troyes': 'France',
 'Neuilly-sur-Seine': 'France',
 'Millau': 'France',
 'Christiania': 'Norway',
 'Zweden': 'Sweden',
 'Lund': 'Sweden',
 'Leszno': 'Poland',
 'Veghel': 'Netherlands',
 'Puria': 'Italy',
 'Denemarken': 'Denmark',
 'Cuba': 'Cuba',
 'Soest (Utrecht)': 'Netherlands',
 'Waulsort': 'Belgium',
 'Siegen': 'Germany',
 'Makkum': 'Netherlands',
 'Terheijden': 'Netherlands',
 'Sandhurst': 'United Kingdom',
 'Waelhem': 'Belgium',
 'Théâtre des Folies-Marigny': nan,
 'Menen': 'Belgium',
 'Aups': 'France',
 'Cluny': 'France',
 'Montigny-le-Gannelon': 'France',
 'Châlons-en-Champagne': 'France',
 'Sint-Jans-Molenbeek': 'Belgium',
 'Namen': 'Belgium',
 'Berchem': 'Belgium',
 'Aalst': 'Belgium',
 "L'Ile-Bouchard": 'France',
 'Helsingør': 'Denmark',
 'Assendelft': 'Netherlands',
 'Goëngamieden': nan,
 'Sint-Oedenrode': 'Netherlands',
 'Hoofdplaat': 'Netherlands',
 'Pordenone': 'Italy',
 'Zwammerdam': 'Netherlands',
 'Barcelona': 'Spain',
 'Granada': 'Spain',
 'Tsjechië': 'Czechia',
 'Laval': 'France',
 'De Lier': 'Netherlands',
 'Kasteel Cannenburgh': 'Netherlands',
 'Luxemburg': 'Luxembourg',
 'Saint-Germain-en-Laye': 'France',
 'Maine': 'United States',
 'Leicestershire': 'United Kingdom',
 'Wroclaw': 'Poland',
 'Drachten': 'Netherlands',
 'Heywood': 'United Kingdom',
 'Bayonne': 'France',
 'Mucklestone': 'United Kingdom',
 'Alterkülz': 'Germany',
 'Chioggia': 'Italy',
 'Moskou': 'Russia',
 'Los Angeles': 'United States',
 'Sneek': 'Netherlands',
 'Rastatt': 'Germany',
 'Burum': 'Netherlands',
 'Montpellier': 'France',
 'Gonneville-la-Mallet': 'France',
 'Münster': 'Germany',
 'Dairsie': 'United Kingdom',
 'Bristol': 'United Kingdom',
 "Saint-Nicolas-d'Attez": 'France',
 'Pieve di Cadore': 'Italy',
 'Saint-Mandé': 'France',
 'Angers': 'France',
 'Cambrai': 'France',
 'Groot Zundert': 'Netherlands',
 'Bergamo': 'Italy',
 'Ljubljana': 'Slovenia',
 'Guernsey': 'Guernsey',
 'Efferen': 'Germany',
 'Augustinusga': 'Netherlands',
 'Enschede': 'Netherlands',
 'Den Helder': 'Netherlands',
 'Sittard': 'Netherlands',
 'Brühl': 'Germany',
 'Schaarbeek': 'Belgium',
 'Beetsterzwaag': 'Netherlands',
 'Melbury (Dorset)': 'United Kingdom',
 'Steubenville': 'United States',
 'Blackheath': 'United Kingdom',
 'Paisley': 'United Kingdom',
 'Wiltshire': 'United Kingdom',
 'Wallington': 'United States',
 'Ridderkerk': 'Netherlands',
 'Wesel': 'Germany',
 'Kochi-ken': 'Japan',
 'Grünbach': 'Germany'}

In [17]:
maker['place_of_birth_country_name'] = maker['place_of_birth'].map(country_dict)
maker.head()

,name,place_of_birth,date_of_birth,date_of_death,place_of_death,nationality,place_of_birth_country_name
0,'t Hooft,NaN,NaN,NaN,NaN,NaN,NaN
1,A. & G. Taylor,NaN,NaN,NaN,NaN,NaN,NaN
2,A. Böeseken,'s-Heerenberg,1834-01-12,1919-02-11,Rotterdam,NaN,Netherlands
3,A. Cucumus & Cie.,NaN,NaN,NaN,NaN,NaN,NaN
4,A. Dandoy,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
from tqdm import tqdm_notebook as tqdm

place_of_death_list = maker['place_of_death'].unique()
country_dict = {}
for place in tqdm(place_of_death_list):
    if place != place:
        continue
    try:
        country = place2country(place)
        country_dict[place] = country
    except:
        # 国名を取得できない場合はnan
        print(place)
        country_dict[place] = np.nan
        
maker['place_of_death_country_name'] = maker['place_of_death'].map(country_dict)
maker.head()

<ipython-input-18-23a7f0d61791>:5: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for place in tqdm(place_of_death_list):

HBox(children=(FloatProgress(value=0.0, max=384.0), HTML(value='')))

Théâtre des Folies-Marigny
Bieberich

,name,place_of_birth,date_of_birth,date_of_death,place_of_death,nationality,place_of_birth_country_name,place_of_death_country_name
0,'t Hooft,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A. & G. Taylor,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A. Böeseken,'s-Heerenberg,1834-01-12,1919-02-11,Rotterdam,NaN,Netherlands,Netherlands
3,A. Cucumus & Cie.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A. Dandoy,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
maker.to_csv('../maker_rename.csv')